// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: rpc_get_payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payments []*Payment `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
}

func (x *GetAllPaymentResponse) Reset() {
	*x = GetAllPaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPaymentResponse) ProtoMessage() {}

func (x *GetAllPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetAllPaymentResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllPaymentResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type GetAllEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllEmpty) Reset() {
	*x = GetAllEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmpty) ProtoMessage() {}

func (x *GetAllEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmpty.ProtoReflect.Descriptor instead.
func (*GetAllEmpty) Descriptor() ([]byte, []int) {
	return file_rpc_get_payment_proto_rawDescGZIP(), []int{1}
}

var File_rpc_get_payment_proto protoreflect.FileDescriptor

var file_rpc_get_payment_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x0d, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x14, 0x5a, 0x12, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_payment_proto_rawDescOnce sync.Once
	file_rpc_get_payment_proto_rawDescData = file_rpc_get_payment_proto_rawDesc
)

func file_rpc_get_payment_proto_rawDescGZIP() []byte {
	file_rpc_get_payment_proto_rawDescOnce.Do(func() {
		file_rpc_get_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_payment_proto_rawDescData)
	})
	return file_rpc_get_payment_proto_rawDescData
}

var file_rpc_get_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_payment_proto_goTypes = []interface{}{
	(*GetAllPaymentResponse)(nil), // 0: pb.GetAllPaymentResponse
	(*GetAllEmpty)(nil),           // 1: pb.GetAllEmpty
	(*Payment)(nil),               // 2: pb.Payment
}
var file_rpc_get_payment_proto_depIdxs = []int32{
	2, // 0: pb.GetAllPaymentResponse.payments:type_name -> pb.Payment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_payment_proto_init() }
func file_rpc_get_payment_proto_init() {
	if File_rpc_get_payment_proto != nil {
		return
	}
	file_payment_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_payment_proto_goTypes,
		DependencyIndexes: file_rpc_get_payment_proto_depIdxs,
		MessageInfos:      file_rpc_get_payment_proto_msgTypes,
	}.Build()
	File_rpc_get_payment_proto = out.File
	file_rpc_get_payment_proto_rawDesc = nil
	file_rpc_get_payment_proto_goTypes = nil
	file_rpc_get_payment_proto_depIdxs = nil
}
