version: '3'

services:
  broker-service:
    container_name: 'broker-service'
    build:
      context: ../broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  # mysql:
  #   image: 'mysql:latest'
  #   container_name: 'mysql_auth'
  #   ports:
  #     - "3300:3306"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   environment:
  #     - MYSQL_DATABASE=users
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_ROOT_PASSWORD=root
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     timeout: 20s
  #     retries: 10
  #   volumes:
  #       - ./volumes/mysql-auth:/var/lib/mysql

  mysql-order:
    image: 'mysql:latest'
    container_name: 'mysql_order'
    ports:
      - "3307:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
        - ./volumes/mysql-order:/var/lib/mysql

  mysql-product:
    image: 'mysql:latest'
    container_name: 'mysql_product'
    ports:
      - "3308:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
        - ./volumes/mysql-product:/var/lib/mysql

  mysql-payment:
    image: 'mysql:latest'
    container_name: 'mysql_payment'
    ports:
      - "3311:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MYSQL_DATABASE=payments
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./volumes/mysql-payment:/var/lib/mysql

  # authentication-service:
  #   container_name: 'authentication-service'
  #   build:
  #     context: ../authentication-service
  #     dockerfile: authentication-service.dockerfile
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   depends_on:
  #     - mysql
  #   environment:
  #     DSN: "admin:password@tcp(mysql_auth:3306)/users?charset=utf8&parseTime=True&loc=Local"

  order-service:
    container_name: 'order-service'
    build:
      context: ../order-service
      dockerfile: order-service.dockerfile
    restart: always
    ports:
      - "8082:80"
#      - "8083:9090" #for grpc
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql-order
    environment:
      DSN: "admin:password@tcp(mysql_order:3306)/orders?charset=utf8&parseTime=True&loc=Local"

  product-service:
    container_name: 'product-service'
    build:
      context: ../product-service
      dockerfile: product-service.dockerfile
    restart: always
    ports:
      - "8084:80"
#      - "8085:9090" #for grpc
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql-product
    environment:
      DSN: "admin:password@tcp(mysql_product:3306)/products?charset=utf8&parseTime=True&loc=Local"

  email-service:
    container_name: 'email-service'
    build:
      context: ../email-service
      dockerfile: email-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  payment-service:
    container_name: 'payment-service'
    build:
      context: ../payment-service
      dockerfile: payment-service.dockerfile
    restart: always
    ports:
      - "8086:80"
#      - "8087:9090" #for grpc
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mysql-payment
    environment:
      DSN: "admin:password@tcp(mysql_payment:3306)/payments?charset=utf8&parseTime=True&loc=Local"
