// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.2
// source: rpc_get_product_detail_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductDetailByProductIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId int64 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *GetProductDetailByProductIDRequest) Reset() {
	*x = GetProductDetailByProductIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_product_detail_by_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductDetailByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailByProductIDRequest) ProtoMessage() {}

func (x *GetProductDetailByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_product_detail_by_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_product_detail_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductDetailByProductIDRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductDetailByProductIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductDetail []*ProductDetail `protobuf:"bytes,1,rep,name=product_detail,json=productDetail,proto3" json:"product_detail,omitempty"`
}

func (x *GetProductDetailByProductIDResponse) Reset() {
	*x = GetProductDetailByProductIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_product_detail_by_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProductDetailByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailByProductIDResponse) ProtoMessage() {}

func (x *GetProductDetailByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_product_detail_by_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_product_detail_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductDetailByProductIDResponse) GetProductDetail() []*ProductDetail {
	if x != nil {
		return x.ProductDetail
	}
	return nil
}

var File_rpc_get_product_detail_by_id_proto protoreflect.FileDescriptor

var file_rpc_get_product_detail_by_id_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x23,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x14, 0x5a,
	0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_product_detail_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_product_detail_by_id_proto_rawDescData = file_rpc_get_product_detail_by_id_proto_rawDesc
)

func file_rpc_get_product_detail_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_product_detail_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_product_detail_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_product_detail_by_id_proto_rawDescData)
	})
	return file_rpc_get_product_detail_by_id_proto_rawDescData
}

var file_rpc_get_product_detail_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_product_detail_by_id_proto_goTypes = []interface{}{
	(*GetProductDetailByProductIDRequest)(nil),  // 0: pb.GetProductDetailByProductIDRequest
	(*GetProductDetailByProductIDResponse)(nil), // 1: pb.GetProductDetailByProductIDResponse
	(*ProductDetail)(nil),                       // 2: pb.ProductDetail
}
var file_rpc_get_product_detail_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetProductDetailByProductIDResponse.product_detail:type_name -> pb.ProductDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_product_detail_by_id_proto_init() }
func file_rpc_get_product_detail_by_id_proto_init() {
	if File_rpc_get_product_detail_by_id_proto != nil {
		return
	}
	file_product_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_product_detail_by_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductDetailByProductIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_product_detail_by_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProductDetailByProductIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_product_detail_by_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_product_detail_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_product_detail_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_product_detail_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_product_detail_by_id_proto = out.File
	file_rpc_get_product_detail_by_id_proto_rawDesc = nil
	file_rpc_get_product_detail_by_id_proto_goTypes = nil
	file_rpc_get_product_detail_by_id_proto_depIdxs = nil
}
